- name: Setup nodejs10.x
  shell: curl -sL https://rpm.nodesource.com/setup_10.x | sudo -E bash -
  tags:
    - nodejs

- name: Installing latest version of node.js
  become: yes
  yum:
    name: nodejs
    state: latest
  tags:
    - nodejs
    - nodejs:install
    - install

- name: Install yarn package
  get_url:
    url: https://dl.yarnpkg.com/rpm/yarn.repo
    dest: /etc/yum.repos.d/yarn.repo
  become: yes
  tags:
    - yarn

- name: Installing yarn
  yum:
    name: yarn
    state: latest
  become: yes
  tags:
    - yarn
    - yarn:install
    - install

- name: Execute yarn
  become: yes
  shell: yarn install --check-files
  tags:
    - yarn